const mongoose = require('mongoose');

const commentSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    text: { type: String, required: true },
  },
  { timestamps: { createdAt: true, updatedAt: false } }
);

const sourceSchema = new mongoose.Schema(
  {
    source: { type: String },
    title: { type: String },
    snippet: { type: String },
    link: { type: String },
    imageUrl: { type: String },
    publishedAt: { type: String },
  },
  { _id: false }
);

const newsSchema = new mongoose.Schema(
  {
    topic: { type: String, required: true },
    title: { type: String },
    summary: { type: String, required: true },
    content: { type: String },
    category: { type: String, default: 'General' },
    tags: { type: [String], default: [] },
    interestOverTime: { type: mongoose.Schema.Types.Mixed, default: null },
    availableSources: { type: [String], default: [] },
    sourceOptions: { type: [sourceSchema], default: [] },
    selectedSource: { type: String, default: null },
    primarySource: { type: String, default: null },
    primaryLink: { type: String, default: null },
    imageUrl: { type: String, default: null },
    externalUrl: { type: String, default: null },
    status: {
      type: String,
      enum: ['draft', 'published'],
      default: 'draft',
    },
    publishedAt: { type: Date },
    isTrending: { type: Boolean, default: true },
    autoGenerated: { type: Boolean, default: false },
    fromNewsApi: { type: Boolean, default: false },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
    comments: [commentSchema],
    generatedAt: { type: Date, default: Date.now },
  },
  { timestamps: true }
);

module.exports = mongoose.model('News', newsSchema);

